(()=>{
'use strict';
const API='https://jhohdvuoyvbzwjumnibc.supabase.co/rest/v1/ai_accounts';
const PERS=['突撃型','鉄壁型','物量型','安定型','対戦狂','ボス狙い型','節約型','気まぐれ型','収集家','育成マニア','イベント派','ランカー','慎重派','ギャンブラー','高速攻略型','研究家'];
let all=[],range=0,sort='id',query='',loading=false;
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}
function tier(id){const n=((id-1)%1000)+1;if(n<=10)return'最強';if(n<=50)return'激強';if(n<=100)return'強い';if(n<=700)return'普通';if(n<=900)return'弱い';return'激弱'}
function row(r){const id=Number(r.account_id)||0;return{...r,id,name:r.name||('AI-'+String(id).padStart(4,'0')),rp:Number(r.rp||0),wins:Number(r.wins||0),losses:Number(r.losses||0),stage:Number(r.stage_clears||0),matches:Number(r.matches||0),skill:Number(r.skill??0),generation:Number(r.generation||1),strategy:r.strategy||'balanced',personality:PERS[hash('p'+id)%PERS.length],tier:tier(id)}}
async function fetchRange(p){const offset=p*1000;const url=API+'?select=*&order=account_id.asc&limit=1000&offset='+offset;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('AIデータ取得失敗 '+r.status);return(await r.json()).map(row)}
function ensureStyle(){if($('ai2000Style'))return;const s=document.createElement('style');s.id='ai2000Style';s.textContent=`#ai2000Overlay{position:fixed;inset:0;z-index:2147483647;background:#0b1020;color:#fff;font-family:system-ui,sans-serif;overflow:auto;padding:14px;box-sizing:border-box}#ai2000Box{max-width:1100px;margin:0 auto}#ai2000Top{display:flex;gap:8px;align-items:center;justify-content:space-between;position:sticky;top:0;background:#0b1020;padding:4px 0 10px;z-index:2}#ai2000Title{font-size:22px;font-weight:900}#ai2000Close{font-size:22px;border:0;border-radius:10px;padding:8px 14px;background:#334155;color:#fff}#ai2000Tabs{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}#ai2000Tabs button{flex:1 1 300px;min-height:48px;border:2px solid #64748b;border-radius:10px;background:#1e293b;color:#fff;font-weight:900;font-size:15px}#ai2000Tabs button.active{background:#2563eb}#ai2000Tools{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}#ai2000Search,#ai2000Sort{min-height:44px;border-radius:9px;border:2px solid #475569;background:#111827;color:#fff;padding:8px 10px;font-size:15px;box-sizing:border-box}#ai2000Search{flex:2 1 260px}#ai2000Sort{flex:1 1 180px}#ai2000Status{padding:10px 0;font-weight:800}#ai2000List{display:grid;gap:8px}.ai2000Row{display:grid;grid-template-columns:60px minmax(180px,1fr) 90px 110px 110px;gap:8px;align-items:center;padding:11px;border:1px solid #334155;border-radius:10px;background:#111827;cursor:pointer}.ai2000Row small{display:block;color:#cbd5e1;margin-top:3px}.ai2000Loading{text-align:center;padding:30px;font-size:18px}@media(max-width:650px){.ai2000Row{grid-template-columns:45px minmax(0,1fr);}.ai2000Row>span:nth-child(n+3){font-size:13px}.ai2000Row>b{grid-row:span 2}.ai2000Row>span:nth-child(3),.ai2000Row>span:nth-child(4),.ai2000Row>span:nth-child(5){display:block}}
`;document.head.appendChild(s)}
function close(){const o=$('ai2000Overlay');if(o)o.remove()}
function detail(a){alert(`AI-${String(a.id).padStart(4,'0')}\n名前：${a.name}\nランク：${a.tier}\n性格：${a.personality}\n戦略：${a.strategy}\nRP：${a.rp}\n勝敗：${a.wins}勝 ${a.losses}敗\nステージ：${a.stage}/144\n対戦数：${a.matches}\n世代：${a.generation}`)}
function render(){const list=$('ai2000List'),status=$('ai2000Status');if(!list||!status)return;let arr=all.filter(a=>a.id>=range*1000+1&&a.id<=range*1000+1000);if(query){const q=query.toLowerCase();arr=arr.filter(a=>a.name.toLowerCase().includes(q)||('AI-'+String(a.id).padStart(4,'0')).toLowerCase().includes(q)||String(a.id).includes(q))}arr.sort((a,b)=>sort==='rp'?b.rp-a.rp:sort==='wins'?b.wins-a.wins:sort==='clears'?b.stage-a.stage:sort==='matches'?b.matches-a.matches:sort==='name'?a.name.localeCompare(b.name,'ja'):a.id-b.id);const lo=range*1000+1,hi=range*1000+1000;status.textContent=`表示：AI-${String(lo).padStart(4,'0')} ～ AI-${String(hi).padStart(4,'0')}　検索結果 ${arr.length}体 / 全2000体`;list.innerHTML=arr.map(a=>`<div class="ai2000Row" data-id="${a.id}"><b>#${a.id}</b><span><strong>🤖 ${esc(a.name)}</strong><small>${esc(a.tier)}　${esc(a.personality)}　戦略：${esc(a.strategy)}</small></span><span>${a.rp} RP</span><span>${a.wins}勝 ${a.losses}敗</span><span>${a.stage}/144</span></div>`).join('')||'<div class="ai2000Loading">該当するAIがありません</div>';list.querySelectorAll('.ai2000Row').forEach(el=>el.onclick=()=>{const a=all.find(x=>x.id===Number(el.dataset.id));if(a)detail(a)})}
async function setRange(p){range=p;const status=$('ai2000Status'),list=$('ai2000List');if(!status||!list)return;document.querySelectorAll('#ai2000Tabs button').forEach((b,i)=>b.classList.toggle('active',i===p));status.textContent=`AI-${String(p*1000+1).padStart(4,'0')} ～ AI-${String(p*1000+1000).padStart(4,'0')} を読み込み中…`;list.innerHTML='<div class="ai2000Loading">読み込み中…</div>';try{all=await fetchRange(p);render()}catch(e){status.textContent='読み込みに失敗しました';list.innerHTML='<div class="ai2000Loading">AIデータを取得できませんでした。もう一度お試しください。</div>';console.error(e)}}
function open(){ensureStyle();close();const o=document.createElement('div');o.id='ai2000Overlay';o.innerHTML='<div id="ai2000Box"><div id="ai2000Top"><div id="ai2000Title">🤖 AIアカウント 2000体</div><button id="ai2000Close" type="button">閉じる</button></div><div id="ai2000Tabs"><button type="button">AI-0001 ～ AI-1000</button><button type="button">AI-1001 ～ AI-2000</button></div><div id="ai2000Tools"><input id="ai2000Search" placeholder="AI番号・名前で検索"><select id="ai2000Sort"><option value="id">AI番号順</option><option value="rp">RP順</option><option value="wins">勝利数順</option><option value="clears">クリア数順</option><option value="matches">対戦数順</option><option value="name">名前順</option></select></div><div id="ai2000Status"></div><div id="ai2000List"></div></div>';document.body.appendChild(o);$('ai2000Close').onclick=close;document.querySelectorAll('#ai2000Tabs button').forEach((b,i)=>b.onclick=()=>setRange(i));$('ai2000Search').oninput=e=>{query=e.target.value.trim();render()};$('ai2000Sort').onchange=e=>{sort=e.target.value;render()};setRange(0)}
function hook(){const b=$('aiManageBtn');if(!b||b.dataset.ai2000Hook)return;if(!b.dataset.ai2000Original)b.dataset.ai2000Original=b.textContent||'';b.dataset.ai2000Hook='1';b.textContent='🤖 2000AIアカウントを確認';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open()},true)}
function boot(){hook();setInterval(hook,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
