(()=>{
const SUPABASE='https://jhohdvuoyvbzwjumnibc.supabase.co';
const PERS=['突撃型','鉄壁型','物量型','安定型','対戦狂','ボス狙い型','節約型','気まぐれ型','収集家','育成マニア','イベント派','ランカー','慎重派','ギャンブラー','高速攻略型','研究家'];
const REWARDS=[{name:'突撃ハーランド木下',cost:777,hp:2500,atk:1500,range:60,spd:2.5,interval:.7,recharge:25,icon:'⚽',motion:'super',attackType:'area',kb:2,series:'日本編章クリア報酬',rarity:'SR',specialReward:true},{name:'異常木下',cost:3000,hp:15000,atk:3000,range:200,spd:.3,interval:.5,recharge:45,icon:'😈',motion:'muscle',attackType:'single',kb:5,series:'日本編章クリア報酬',rarity:'SSR',specialReward:true},{name:'吉田',cost:200,hp:6000,atk:1111,range:100,spd:1.2,interval:.65,recharge:3,icon:'🧑🏻',motion:'power',attackType:'area',kb:2,series:'日本編章クリア報酬',rarity:'SR',specialReward:true}];
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}
function tier(id){const x=((id-1)%1000)+1;if(x<=10)return['最強',90,99.5];if(x<=50)return['激強',78,94];if(x<=100)return['強い',65,86];if(x<=700)return['普通',38,72];if(x<=900)return['弱い',22,55];return['激弱',8,36]}
function mapRow(r){const id=Number(r.account_id)||0,t=tier(id);return{accountId:'AI-'+String(id).padStart(4,'0'),name:r.name||('AI-'+String(id).padStart(4,'0')),rp:Number(r.rp||0),skill:Number(r.skill??.25),wins:Number(r.wins||0),losses:Number(r.losses||0),generation:Number(r.generation||1),strategy:r.strategy||'balanced',aggression:Number(r.aggression??.5),save:Number(r.save_rate??.5),formation:Array.isArray(r.formation)?r.formation:[],stageClears:Number(r.stage_clears||0),chapterClears:Array.isArray(r.chapter_clears)?r.chapter_clears:[0,0,0],ownedCharacters:Array.isArray(r.owned_characters)?r.owned_characters:[0],eventClears:r.event_clears&&typeof r.event_clears==='object'?r.event_clears:{},charLevels:Array.isArray(r.char_levels)?r.char_levels:[],trainingXP:Number(r.training_xp||0),matches:Number(r.matches||0),lastResult:r.last_result||'',matchHistory:Array.isArray(r.match_history)?r.match_history:[],coins:Number(r.coins||900),playerXP:Number(r.player_xp||0),workerLevel:Number(r.worker_level||1),activity:typeof r.activity==='object'?(r.activity?.text||r.activity?.message||'待機中'):(r.activity||'待機中'),activityHistory:Array.isArray(r.activity_history)?r.activity_history:[],tierLabel:t[0],personality:PERS[hash('p'+id)%PERS.length],aiStrength:Math.round(t[1]+(hash('s'+id)%10000)/10000*(t[2]-t[1]))}}
async function getRows(offset){const r=await fetch(SUPABASE+'/rest/v1/ai_accounts?select=*&order=account_id.asc&limit=1000&offset='+offset,{cache:'no-store'});if(!r.ok)throw Error('AI '+r.status);return r.json()}
let page=0,allAI=[],loaded=false;
function renderVisible(){const list=document.getElementById('aiAccountList'),count=document.getElementById('aiAccountCount');if(!list||!loaded)return;const q=(document.getElementById('aiSearchInput')?.value||'').trim().toLowerCase();const sort=document.getElementById('aiSortSelect')?.value||'rp';let arr=allAI.map((a,i)=>({a,i})).filter(x=>!q||x.a.name.toLowerCase().includes(q)||x.a.accountId.toLowerCase().includes(q)||String(x.i+1).includes(q));arr.sort((x,y)=>{const a=x.a,b=y.a;if(sort==='matches')return b.matches-a.matches;if(sort==='wins')return b.wins-a.wins;if(sort==='clears')return b.stageClears-a.stageClears;if(sort==='generation')return b.generation-a.generation;if(sort==='name')return a.name.localeCompare(b.name,'ja');return b.rp-a.rp});const start=page*1000,end=Math.min(start+1000,arr.length);const visible=arr.slice(start,end);count.textContent=`表示：AI-${String(start+1).padStart(4,'0')} ～ AI-${String(end).padStart(4,'0')}（全${allAI.length}体）`;list.innerHTML=visible.map(x=>{const a=x.a;return `<div class="aiAccountRow" data-ai-index="${x.i}"><b>#${x.i+1}</b><span>🤖 ${a.name}<small>${a.tierLabel||''}　${a.personality||''}　${typeof strategyOf==='function'?strategyOf(a).label:(a.strategy||'')}</small></span><span>${a.rp} RP</span><span>${a.wins}勝 ${a.losses}敗</span><span>${a.stageClears}/144ステージ</span></div>`}).join('');list.querySelectorAll('.aiAccountRow').forEach(row=>row.onclick=()=>{if(typeof openAIDetail==='function')openAIDetail(Number(row.dataset.aiIndex))})}
function makeTabs(){if(document.getElementById('aiRangeTabs'))return;const list=document.getElementById('aiAccountList');if(!list)return;const panel=list.closest('.panel')||list.parentElement;if(!panel)return;const box=document.createElement('div');box.id='aiRangeTabs';box.style.cssText='display:flex!important;gap:10px!important;flex-wrap:wrap!important;margin:10px 0 12px!important;padding:8px!important;background:#0f172a!important;border:2px solid #475569!important;border-radius:12px!important;position:relative!important;z-index:2147483647!important;width:100%!important;box-sizing:border-box!important;';for(let p=0;p<2;p++){const b=document.createElement('button');b.type='button';b.textContent=p===0?'AI-0001 ～ AI-1000':'AI-1001 ～ AI-2000';b.style.cssText='display:block!important;visibility:visible!important;opacity:1!important;flex:1 1 220px!important;min-height:48px!important;padding:10px 12px!important;border:2px solid #64748b!important;border-radius:10px!important;background:#1e293b!important;color:#fff!important;font-weight:1000!important;font-size:15px!important;cursor:pointer!important;touch-action:manipulation!important;';b.onclick=()=>{page=p;box.querySelectorAll('button').forEach((x,i)=>{x.style.background=i===p?'#2563eb':'#1e293b'});renderVisible()};box.appendChild(b)}box.querySelectorAll('button')[0].style.background='#2563eb';const h1=panel.querySelector('h1');if(h1&&h1.nextSibling)panel.insertBefore(box,h1.nextSibling);else panel.insertBefore(box,panel.firstChild)}
async function sync(){try{const[r1,r2]=await Promise.all([getRows(0),getRows(1000)]);allAI=[...(Array.isArray(r1)?r1:[]),...(Array.isArray(r2)?r2:[])].sort((a,b)=>Number(a.account_id)-Number(b.account_id)).slice(0,2000).map(mapRow);loaded=true;makeTabs();renderVisible();if(typeof renderRankLeaderboard==='function')renderRankLeaderboard();const m=document.getElementById('aiManageBtn');if(m)m.textContent='🤖 2000AIアカウントを確認';}catch(e){console.warn('AI2000同期失敗',e)}}
function patch(){if(typeof cards!=='undefined')for(const c of REWARDS)if(!cards.some(x=>x&&x.name===c.name))cards.push(c);if(typeof allyTraits!=='undefined'){allyTraits['突撃ハーランド木下']='無';allyTraits['異常木下']='赤';allyTraits['吉田']='赤'}makeTabs();if(loaded)renderVisible();const m=document.getElementById('aiManageBtn');if(m)m.textContent='🤖 2000AIアカウントを確認'}
patch();setTimeout(sync,0);setInterval(()=>{try{patch()}catch(e){}},1000);
})();
