const CACHE_NAME="kinoshita-daisen-v8";
const APP_SHELL=["./","./index.html","./manifest.json","./icon-192.png","./icon-512.png"];
const REWARDS=[{name:"突撃ハーランド木下",cost:777,hp:2500,atk:1500,range:60,spd:2.5,interval:.7,recharge:25,icon:"⚽",motion:"super",attackType:"area",kb:2,series:"日本編章クリア報酬",rarity:"SR",specialReward:true},{name:"異常木下",cost:3000,hp:15000,atk:3000,range:200,spd:.3,interval:.5,recharge:45,icon:"😈",motion:"muscle",attackType:"single",kb:5,series:"日本編章クリア報酬",rarity:"SSR",specialReward:true},{name:"吉田",cost:200,hp:6000,atk:1111,range:100,spd:1.2,interval:.65,recharge:3,icon:"🧑🏻",motion:"power",attackType:"area",kb:2,series:"日本編章クリア報酬",rarity:"SR",specialReward:true}];
const PERS=["突撃型","鉄壁型","物量型","安定型","対戦狂","ボス狙い型","節約型","気まぐれ型","収集家","育成マニア","イベント派","ランカー","慎重派","ギャンブラー","高速攻略型","研究家"];
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}
function tier(id){const x=((id-1)%1000)+1;if(x<=10)return["最強",.90,.995];if(x<=50)return["激強",.78,.94];if(x<=100)return["強い",.65,.86];if(x<=700)return["普通",.38,.72];if(x<=900)return["弱い",.22,.55];return["激弱",.08,.36]}
function decorate(a){const id=Number(String(a.account_id||a.accountId||"0").replace(/\D/g,""))||0;const t=tier(id);a.tierLabel=t[0];a.personality=PERS[hash("p"+id)%PERS.length];a.aiStrength=Math.round((t[1]+(hash("s"+id)%10000)/10000*(t[2]-t[1]))*100);if(a.activity&&typeof a.activity==="object")a.activity=a.activity.text||a.activity.message||"待機中";if(Array.isArray(a.activity_history))a.activity_history=a.activity_history.map(x=>typeof x==="string"?x:(x&&typeof x==="object"?(x.text||x.message||x.activity||"活動記録"):String(x)));return a}
async function transformAIResponse(request,response){try{const rows=await response.clone().json();if(!Array.isArray(rows))return response;const u=new URL(request.url);u.search="?select=*&account_id=gt.1000&order=account_id.asc&limit=1000";let extra=[];try{const er=await fetch(new Request(u.toString(),{method:"GET",headers:request.headers}));if(er.ok){const j=await er.json();if(Array.isArray(j))extra=j}}catch(e){}const merged=[...rows,...extra].sort((a,b)=>Number(a.account_id)-Number(b.account_id)).slice(0,2000).map(decorate);const h=new Headers(response.headers);h.set("content-type","application/json");return new Response(JSON.stringify(merged),{status:response.status,statusText:response.statusText,headers:h})}catch(e){return response}}
const PATCH=`if(!window.__aiV8){window.__aiV8=true;const rewardCards=${JSON.stringify(REWARDS)};const pers=${JSON.stringify(PERS)};const hv=s=>{let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0};if(typeof cards!=="undefined"){for(const c of rewardCards){if(!cards.some(x=>x&&x.name===c.name))cards.push(c)}}if(typeof allyTraits!=="undefined"){allyTraits["突撃ハーランド木下"]="無";allyTraits["異常木下"]="赤";allyTraits["吉田"]="赤"}if(typeof chapterClears!=="undefined"&&typeof ownedFlags!=="undefined")setInterval(()=>{for(let i=0;i<3;i++){const c=cards.findIndex(x=>x&&x.name===rewardCards[i].name);if(c>=0&&Number(chapterClears[i]||0)>=48)ownedFlags[c]=true}},500);function decorateLocalAI(a,i){const id=Number(String(a.accountId||("AI-"+(i+1))).replace(/\D/g,""))||i+1,x=((id-1)%1000)+1,t=x<=10?["最強",90,99.5]:x<=50?["激強",78,94]:x<=100?["強い",65,86]:x<=700?["普通",38,72]:x<=900?["弱い",22,55]:["激弱",8,36];a.tierLabel=t[0];a.personality=pers[hv("p"+id)%pers.length];a.aiStrength=Math.round(t[1]+(hv("s"+id)%10000)/10000*(t[2]-t[1]));if(a.activity&&typeof a.activity==="object")a.activity=a.activity.text||a.activity.message||"待機中";if(Array.isArray(a.activityHistory))a.activityHistory=a.activityHistory.map(x=>typeof x==="string"?x:(x&&typeof x==="object"?(x.text||x.message||x.activity||"活動記録"):String(x)));return a}if(typeof aiProfiles!=="undefined"&&Array.isArray(aiProfiles)){aiProfiles.forEach(decorateLocalAI);setInterval(()=>aiProfiles.forEach(decorateLocalAI),1000)}if(typeof renderAIAccountList==="function"){const old=renderAIAccountList;renderAIAccountList=function(){old();const el=document.getElementById("aiAccountList"),count=document.getElementById("aiAccountCount");if(count)count.textContent=`表示：${aiProfiles.length} / 2000アカウント`;if(el)el.querySelectorAll(".aiAccountRow").forEach(r=>{const a=aiProfiles[Number(r.dataset.aiIndex)],s=r.querySelector("small");if(a&&s)s.textContent=`${a.tierLabel||"普通"}　${a.personality||"安定型"}　AI強度 ${a.aiStrength||50}%`})}}}`;
function transformHtml(text){if(text.includes("__aiV8"))return text;const p=text.lastIndexOf("</script>");return p<0?text:text.slice(0,p)+"\n"+PATCH+"\n"+text.slice(p)}
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(APP_SHELL)))});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE_NAME).map(x=>caches.delete(x)))).then(()=>self.clients.claim()))});
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=e.request.url;if(u.includes("/rest/v1/ai_accounts")){e.respondWith(fetch(e.request).then(r=>transformAIResponse(e.request,r)).catch(()=>caches.match(e.request)));return}e.respondWith(fetch(e.request).then(async r=>{const type=r.headers.get("content-type")||"";if(type.includes("text/html")){const text=await r.clone().text();const out=new Response(transformHtml(text),{status:r.status,statusText:r.statusText,headers:r.headers});caches.open(CACHE_NAME).then(c=>c.put(e.request,out.clone()));return out}caches.open(CACHE_NAME).then(c=>c.put(e.request,r.clone()));return r}).catch(()=>caches.match(e.request)))});
