-- 木下大戦争：プレイヤーアンケート
-- Supabase SQL Editorで実行してください（プロジェクトのEgress制限が解除されてから）。
create table if not exists public.game_surveys (
  id bigint generated by default as identity primary key,
  survey_id text not null,
  player_id text not null,
  answers jsonb not null,
  created_at timestamptz not null default now(),
  constraint game_surveys_survey_player_unique unique (survey_id, player_id),
  constraint game_surveys_answers_object check (jsonb_typeof(answers) = 'object')
);

alter table public.game_surveys enable row level security;

grant select, insert on public.game_surveys to anon, authenticated;
grant usage, select on sequence public.game_surveys_id_seq to anon, authenticated;

drop policy if exists "Anyone can read public survey answers" on public.game_surveys;
create policy "Anyone can read public survey answers"
  on public.game_surveys for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can submit one survey per player and survey" on public.game_surveys;
create policy "Anyone can submit one survey per player and survey"
  on public.game_surveys for insert
  to anon, authenticated
  with check (
    char_length(survey_id) between 1 and 100
    and char_length(player_id) between 1 and 100
    and jsonb_typeof(answers) = 'object'
  );
